version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - .:/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app