version: '3.9'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"  # Adjust port mapping if needed (currently exposes 5000 on host)
    env_file:
      - .env
    volumes:
      - .:/app